---
ci:
  skip: [hadolint-docker]

repos:
  # Autoupdate: Python code
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.26.0
    hooks:
      - id: pyupgrade
        args: [--py39-plus]

  # Autoformat: Python code
  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black
        args: [--target-version=py39]

  # Autoformat: YAML, JSON, Markdown, etc.
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.4.1
    hooks:
      - id: prettier
        exclude: "{{cookiecutter.stack_name}}/.github/workflows/docker.yml"

  # Lint: Dockerfile
  - repo: https://github.com/hadolint/hadolint.git
    rev: v2.7.0
    hooks:
      - id: hadolint-docker

  # Lint: YAML
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.3
    hooks:
      - id: yamllint
        args: ["-d {extends: relaxed, rules: {line-length: disable}}", "-s"]
        files: \.(yaml|yml)$
        exclude: "{{cookiecutter.stack_name}}/.github/workflows/docker.yml"

  # Lint: Python
  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8

  # Lint: Markdown
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.28.1
    hooks:
      - id: markdownlint
        args: ["--fix"]
