name: Build Docker Images 

# For more details on events that trigger workflows see:
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  pull_request:
    paths-ignore:
      - "*.md"
      - "binder/**"
      - "docs/**"
      - "examples/**"
  push:
    branches:
      - master
    paths-ignore:
      - "*.md"
      - "binder/**"
      - "docs/**"
      - "examples/**"

jobs:
  build:
    name: Build Docker Images 
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Dev Dependencies
        run: |
          python -m pip install --upgrade pip
          make test-env
      - name: Build Docker Images
        run: |
          make build 
          make test
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ----
          password: ----