name: Run Tests 

on: 
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs: 
  test:
    name: Run Tests 
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Set Up Python 
        uses: actions/setup-python@v2
        with: 
          python-version: 3.8
      - name: Install Dev Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-test.txt
      - name: Run tests 
        run: make test
